<?php
/**
 * Autogenerated by Thrift Compiler (0.9.2)-v1.0.1
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR YOUZAN, ANY PROBLEM PLS CONTACT lanhu(zhangyuanhao@qima-inc.com)
 * qingjiao(qingjiao@qima-inc.com) & xiao'er(shiyu@qima-inc.com)
 * @generated
 */

namespace Com\Youzan\Demo\Service;

use Kdt\Iron\Nova\Foundation\Protocol\TStruct;
use Thrift\Type\TType;


class MixedStruct extends TStruct {
  /**
   * @var string
   */
  public $propString = null;
  /**
   * @var \Com\Youzan\Demo\Service\BaseStruct
   */
  public $baseStruct = null;
  /**
   * @var \Com\Youzan\Demo\Service\BaseStruct[]
   */
  public $propList = null;
  /**
   * @var \Com\Youzan\Demo\Service\BaseStruct[]
   */
  public $propSet = null;
  /**
   * @var array
   */
  public $propMap = null;

  protected $structSpec = [
    1 => [
      'var' => 'propString',
      'type' => TType::STRING,
      ],
    2 => [
      'var' => 'baseStruct',
      'type' => TType::STRUCT,
      'class' => '\Com\Youzan\Demo\Service\BaseStruct',
      ],
    3 => [
      'var' => 'propList',
      'type' => TType::LST,
      'etype' => TType::STRUCT,
      'elem' => [
        'type' => TType::STRUCT,
        'class' => '\Com\Youzan\Demo\Service\BaseStruct',
        ],
      ],
    4 => [
      'var' => 'propSet',
      'type' => TType::SET,
      'etype' => TType::STRUCT,
      'elem' => [
        'type' => TType::STRUCT,
        'class' => '\Com\Youzan\Demo\Service\BaseStruct',
        ],
      ],
    5 => [
      'var' => 'propMap',
      'type' => TType::MAP,
      'ktype' => TType::STRING,
      'vtype' => TType::STRUCT,
      'key' => [
        'type' => TType::STRING,
      ],
      'val' => [
        'type' => TType::STRUCT,
        'class' => '\Com\Youzan\Demo\Service\BaseStruct',
        ],
      ],
    ];

}

