/**
 * Autogenerated by Thrift Compiler (0.9.2)-v1.0.1
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR YOUZAN, ANY PROBLEM PLS CONTACT lanhu(zhangyuanhao@qima-inc.com)
 * qingjiao(qingjiao@qima-inc.com) & xiao'er(shiyu@qima-inc.com)
 * @generated
 */
package com.youzan.demo.service;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorLevel implements org.apache.thrift.TEnum {
  DEBUG(1),
  INFO(2),
  WARN(3),
  ERROR(4);

  private final int value;

  private ErrorLevel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorLevel findByValue(int value) { 
    switch (value) {
      case 1:
        return DEBUG;
      case 2:
        return INFO;
      case 3:
        return WARN;
      case 4:
        return ERROR;
      default:
        return null;
    }
  }
}
